
user_languages = {}

def translate(key, lang="en"):
    return translations.get(lang, translations["en"]).get(key, key)

translations = {
    "en": {
        "User select an option": "User select an option",
        "db_error": "Database error",
        "language_set_en": "Language set to English.",
        "choose_language": "Choose language: /en /ru /uk /pol",
        "language_set": "Language set to English.",
        "Show my favorite watches:": "Show my favorite watches:",
        "Delete watch": "Delete watch",
        "Welcome to the Watches Bot! Choose a watch:": "Welcome to the Watches Bot! Choose a watch:",
        "Choose a watch:": "Choose a watch:",
        "and select an action:": "and select an action:",
        "no_favorite_watches": "You don't have any favorite watches",
        "your_favorite_watches": "Your favorite watches",
        "Name": "Name",
        "Characteristics": "Characteristics",
        "Price": "Price",
        "Delete": "Delete",
        "you_delete_your_favorite_watches": "You deleted your favorite watches",
        "write_watch_name": "Write the name of the watch you want to find",
        "no_watches_found": "No watches found for your selection",
        "All your favorite watches have been deleted": "All your favorite watches have been deleted.",
        "Select an option": "Select an option",
        "Select an option:": "Select an option:",
        "Show my favorite watches": "Show my favorite watches",
        "all_your_favorite_watches_have_been_deleted": "All your favorite watches have been deleted.",
        "Please select a watch brand first.": "Please select a watch brand first.",
        "No watches found for your selection.": "No watches found for your selection.",
        "Choose price from:": "Choose price from:",
        "Choose price to:": "Choose price to:",
        "Added to watchlist!": "Added to watchlist!",
        "Please select a watch brand first": "Please select a watch brand first",
        "No price found in": "No price found in",
        "Price range is not set. Please select price range again.": "Price range is not set. Please select price range again.",
        "Send /more to see more watches.": "Send /more to see more watches.",
        "No more watches.": "No more watches.",
        "unknown_command": "Unknown command. Please use the menu",
        "Follow": "Follow",
        "Added to watchlist": "Added to watchlist",
        "Choose price from": "Choose price from",
        "Choose price to": "Choose price to",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "You have selected {watch_name} in the range: from {price_from} to {price_to}. Do you want to see watches? Type /watches.",
        "favorite_watch_callback DB error": "Favorite watch callback database error",
        "watch_info_format": "Name: {name}\nCharacteristics: {characteristics}\nPrice: {price}",
        "tracking_added_format": "You have added to tracking:\nName: {name}\nCharacteristics: {characteristics}\nPrice: {price}",
        "tracking_added_message": "You have added to tracking:",
    },
    "ru": {
        "User select an option": "Пользователь выберите опцию",
        "user_select_an_option": "Пользователь выберите опцию",
        "db_error": "Ошибка базы данных",
        "you_delete_your_favorite_watches": "Вы удалили свои избранные часы",
        "language_set_ru": "Язык переключен на русский.",
        "choose_language": "Выберите язык: /en /ru /uk /pol",
        "language_set": "Язык переключен на русский.",
        "Show my favorite watches:": "Показать мои избранные часы:",
        "Delete watch": "Удалить часы",
        "Welcome to the Watches Bot! Choose a watch:": "Добро пожаловать в Watches Bot! Выберите часы:",
        "Choose a watch:": "Выберите часы:",
        "and select an action:": "и выберите действие:",
        "no_favorite_watches": "У вас нет избранных часов",
        "your_favorite_watches": "Ваши избранные часы",
        "Name": "Название",
        "Characteristics": "Характеристики",
        "Price": "Цена",
        "Delete": "Удалить",
        "You delete your favorite watches": "Вы удалили свои избранные часы",
        "write_watch_name": "Напишите название часов, которые хотите найти",
        "no_watches_found": "По вашему запросу часы не найдены",
        "All your favorite watches have been deleted": "Все ваши избранные часы были удалены.",
        "Select an option": "Выберите опцию",
        "Please select a watch brand first": "Пожалуйста, сначала выберите бренд часов",
        "No price found in": "Цена не найдена в",
        "Price range is not set. Please select price range again.": "Диапазон цен не установлен. Пожалуйста, выберите диапазон цен снова.",
        "Send /more to see more watches.": "Отправьте /more, чтобы увидеть больше часов.",
        "No more watches.": "Больше нет часов.",
        "unknown_command": "Неизвестная команда. Пожалуйста, используйте меню",
        "Follow": "Следить",
        "Added to watchlist": "Добавлено в отслеживаемое",
        "Added to watchlist!": "Добавлено в отслеживаемое!",
        "Choose price from": "Выберите цену от",
        "Choose price from:": "Выберите цену от:",
        "Choose price to": "Выберите цену до",
        "Choose price to:": "Выберите цену до:",
        "Select an option:": "Выберите опцию:",
        "Show my favorite watches": "Показать мои избранные часы",
        "all_your_favorite_watches_have_been_deleted": "Все ваши избранные часы были удалены.",
        "Please select a watch brand first.": "Пожалуйста, сначала выберите бренд часов.",
        "No watches found for your selection.": "По вашему запросу часы не найдены.",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Вы выбрали {watch_name} в диапазоне: от {price_from} до {price_to}. Хотите посмотреть часы? Введите /watches.",
        "favorite_watch_callback DB error": "Ошибка базы данных избранных часов",
        "watch_info_format": "Название: {name}\nХарактеристики: {characteristics}\nЦена: {price}",
        "tracking_added_format": "Вы добавили в отслеживание:\nНазвание: {name}\nХарактеристики: {characteristics}\nЦена: {price}",
        "tracking_added_message": "Вы добавили в отслеживание:",
    },
    "uk": {
        "User select an option": "Користувач оберіть опцію",
        "user_select_an_option": "Користувач оберіть опцію",
        "db_error": "Помилка бази даних",
        "you_delete_your_favorite_watches": "Ви видалили свої вибрані годинники",
        "language_set_uk": "Мова переключена на українську.",
        "choose_language": "Оберіть мову: /en /ru /uk /pol",
        "language_set": "Мова переключена на українську.",
        "Show my favorite watches:": "Показати мої вибрані годинники:",
        "Delete watch": "Видалити годинник",
        "Welcome to the Watches Bot! Choose a watch:": "Ласкаво просимо до Watches Bot! Оберіть годинник:",
        "Choose a watch:": "Оберіть годинник:",
        "and select an action:": "та оберіть дію:",
        "no_favorite_watches": "У вас немає вибраних годинників",
        "your_favorite_watches": "Ваші вибрані годинники",
        "Name": "Назва",
        "Characteristics": "Характеристики",
        "Price": "Ціна",
        "Delete": "Видалити",
        "You delete your favorite watches": "Ви видалили свої вибрані годинники",
        "write_watch_name": "Напишіть назву годинника, який хочете знайти",
        "no_watches_found": "За вашим запитом годинники не знайдено",
        "All your favorite watches have been deleted": "Всі ваші вибрані годинники були видалені.",
        "Select an option": "Оберіть опцію",
        "Please select a watch brand first": "Будь ласка, спочатку оберіть бренд годинника",
        "No price found in": "Ціну не знайдено в",
        "Price range is not set. Please select price range again.": "Діапазон цін не встановлено. Будь ласка, оберіть діапазон цін ще раз.",
        "Send /more to see more watches.": "Надішліть /more, щоб побачити більше годинників.",
        "No more watches.": "Більше немає годинників.",
        "unknown_command": "Невідома команда. Будь ласка, скористайтеся меню",
        "Follow": "Стежити",
        "Added to watchlist": "Додано до списку відстеження",
        "Added to watchlist!": "Додано до списку відстеження!",
        "Choose price from": "Оберіть ціну від",
        "Choose price from:": "Оберіть ціну від:",
        "Choose price to": "Оберіть ціну до",
        "Choose price to:": "Оберіть ціну до:",
        "Select an option:": "Оберіть опцію:",
        "Show my favorite watches": "Показати мої вибрані годинники",
        "all_your_favorite_watches_have_been_deleted": "Всі ваші вибрані годинники були видалені.",
        "Please select a watch brand first.": "Будь ласка, спочатку оберіть бренд годинника.",
        "No watches found for your selection.": "За вашим запитом годинники не знайдено.",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Ви обрали {watch_name} у діапазоні: від {price_from} до {price_to}. Бажаєте переглянути годинники? Введіть /watches.",
        "favorite_watch_callback DB error": "Помилка бази даних улюблених годинників",
        "watch_info_format": "Назва: {name}\nХарактеристики: {characteristics}\nЦіна: {price}",
        "tracking_added_format": "Ви додали в відстеження:\nНазва: {name}\nХарактеристики: {characteristics}\nЦіна: {price}",
        "tracking_added_message": "Ви додали в відстеження:",
    },
    "pol": {
        "User select an option": "Użytkownik wybierz opcję",
        "user_select_an_option": "Użytkownik wybierz opcję",
        "db_error": "Błąd bazy danych",
        "you_delete_your_favorite_watches": "Usunąłeś swoje wybrane zegarki",
        "language_set_pol": "Język zmieniony na polski.",
        "choose_language": "Wybierz język: /en /ru /uk /pol",
        "language_set": "Język zmieniony na polski.",
        "Show my favorite watches:": "Pokaż moje wybrane zegarki:",
        "Delete watch": "Usuń zegarek",
        "Welcome to the Watches Bot! Choose a watch:": "Witamy w Watches Bot! Wybierz zegarek:",
        "Choose a watch:": "Wybierz zegarek:",
        "and select an action:": "i wybierz akcję:",
        "no_favorite_watches": "Nie masz wybranych zegarków",
        "your_favorite_watches": "Twoje wybrane zegarki",
        "Name": "Nazwa",
        "Characteristics": "Charakterystyka",
        "Price": "Cena",
        "Delete": "Usuń",
        "You delete your favorite watches": "Usunąłeś swoje wybrane zegarki",
        "write_watch_name": "Napisz nazwę zegarka, który chcesz znaleźć",
        "no_watches_found": "Nie znaleziono zegarków dla Twojego wyboru",
        "All your favorite watches have been deleted": "Wszystkie Twoje wybrane zegarki zostały usunięte.",
        "Select an option": "Wybierz opcję",
        "Please select a watch brand first": "Najpierw wybierz markę zegarka",
        "No price found in": "Nie znaleziono ceny w",
        "Price range is not set. Please select price range again.": "Zakres cen nie jest ustawiony. Wybierz zakres cen ponownie.",
        "Send /more to see more watches.": "Wyślij /more, aby zobaczyć więcej zegarków.",
        "No more watches.": "Nie ma więcej zegarków.",
        "unknown_command": "Nieznane polecenie. Skorzystaj z menu",
        "Follow": "Obserwuj",
        "Added to watchlist": "Dodano do listy obserwowanych",
        "Added to watchlist!": "Dodano do listy obserwowanych!",
        "Choose price from": "Wybierz cenę od",
        "Choose price from:": "Wybierz cenę od:",
        "Choose price to": "Wybierz cenę do",
        "Choose price to:": "Wybierz cenę do:",
        "Select an option:": "Wybierz opcję:",
        "Show my favorite watches": "Pokaż moje ulubione zegarki",
        "all_your_favorite_watches_have_been_deleted": "Wszystkie Twoje ulubione zegarki zostały usunięte.",
        "Please select a watch brand first.": "Najpierw wybierz markę zegarka.",
        "No watches found for your selection.": "Nie znaleziono zegarków dla Twojego wyboru.",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Wybrałeś {watch_name} w zakresie: od {price_from} do {price_to}. Chcesz zobaczyć zegarki? Wpisz /watches.",
        "favorite_watch_callback DB error": "Błąd bazy danych ulubionych zegarków",
        "watch_info_format": "Nazwa: {name}\nCharakterystyka: {characteristics}\nCena: {price}",
        "tracking_added_format": "Dodałeś do śledzenia:\nNazwa: {name}\nCharakterystyka: {characteristics}\nCena: {price}",
        "tracking_added_message": "Dodałeś do śledzenia:",
    }
}