
user_languages = {}

def translate(key, lang="en"):
    return translations.get(lang, translations["en"]).get(key, key)

translations = {
    "en": {
        "Show my favorite watches:": "Show my favorite watches:",
        "Delete watch": "Delete watch",
        "Welcome to the Watches Bot! Choose a watch:": "Welcome to the Watches Bot! Choose a watch:",
        "Choose a watch:": "Choose a watch:",
        "and select an action": "and select an action",
        "You don't have any favorite watches": "You don't have any favorite watches",
        "Your favorite watches": "Your favorite watches",
        "Name": "Name",
        "Characteristics": "Characteristics",
        "Price": "Price",
        "Delete": "Delete",
        "You delete your favorite watches": "You deleted your favorite watches",
        "write the name of the watch you want to find": "Write the name of the watch you want to find",
        "No watches found for your selection": "No watches found for your selection",
        "All your favorite watches have been deleted": "All your favorite watches have been deleted.",
        "Select an option": "Select an option",
        "Please select a watch brand first": "Please select a watch brand first",
        "No price found in": "No price found in",
        "Price range is not set. Please select price range again.": "Price range is not set. Please select price range again.",
        "Send /more to see more watches.": "Send /more to see more watches.",
        "No more watches.": "No more watches.",
        "Unknown command. Please use the menu": "Unknown command. Please use the menu",
        "Follow": "Follow",
        "Added to watchlist": "Added to watchlist",
        "Choose price from": "Choose price from",
        "Choose price to": "Choose price to",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "You have selected {watch_name} in the range: from {price_from} to {price_to}. Do you want to see watches? Type /watches.",
    },
    "ru": {
        "Show my favorite watches:": "Показать мои любимые часы:",
        "Delete watch": "Удалить часы",
        "Welcome to the Watches Bot! Choose a watch:": "Добро пожаловать в Watches Bot! Выберите часы:",
        "Choose a watch:": "Выберите часы:",
        "and select an action": "и выберите действие",
        "You don't have any favorite watches": "У вас нет любимых часов",
        "Your favorite watches": "Ваши любимые часы",
        "Name": "Название",
        "Characteristics": "Характеристики",
        "Price": "Цена",
        "Delete": "Удалить",
        "You delete your favorite watches": "Вы удалили свои любимые часы",
        "write the name of the watch you want to find": "Напишите название часов, которые хотите найти",
        "No watches found for your selection": "По вашему запросу часы не найдены",
        "All your favorite watches have been deleted": "Все ваши любимые часы были удалены.",
        "Select an option": "Выберите опцию",
        "Please select a watch brand first": "Пожалуйста, сначала выберите бренд часов",
        "No price found in": "Цена не найдена в",
        "Price range is not set. Please select price range again.": "Диапазон цен не установлен. Пожалуйста, выберите диапазон цен снова.",
        "Send /more to see more watches.": "Отправьте /more, чтобы увидеть больше часов.",
        "No more watches.": "Больше нет часов.",
        "Unknown command. Please use the menu": "Неизвестная команда. Пожалуйста, используйте меню",
        "Follow": "Следить",
        "Added to watchlist": "Добавлено в отслеживаемое",
        "Choose price from": "Выберите цену от",
        "Choose price to": "Выберите цену до",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Вы выбрали {watch_name} в диапазоне: от {price_from} до {price_to}. Хотите посмотреть часы? Введите /watches.",
    },
    "uk": {
        "Show my favorite watches:": "Показати мої улюблені годинники:",
        "Delete watch": "Видалити годинник",
        "Welcome to the Watches Bot! Choose a watch:": "Ласкаво просимо до Watches Bot! Оберіть годинник:",
        "Choose a watch:": "Оберіть годинник:",
        "and select an action": "та оберіть дію",
        "You don't have any favorite watches": "У вас немає улюблених годинників",
        "Your favorite watches": "Ваші улюблені годинники",
        "Name": "Назва",
        "Characteristics": "Характеристики",
        "Price": "Ціна",
        "Delete": "Видалити",
        "You delete your favorite watches": "Ви видалили свої улюблені годинники",
        "write the name of the watch you want to find": "Напишіть назву годинника, який хочете знайти",
        "No watches found for your selection": "За вашим запитом годинники не знайдено",
        "All your favorite watches have been deleted": "Всі ваші улюблені годинники були видалені.",
        "Select an option": "Оберіть опцію",
        "Please select a watch brand first": "Будь ласка, спочатку оберіть бренд годинника",
        "No price found in": "Ціну не знайдено в",
        "Price range is not set. Please select price range again.": "Діапазон цін не встановлено. Будь ласка, оберіть діапазон цін ще раз.",
        "Send /more to see more watches.": "Надішліть /more, щоб побачити більше годинників.",
        "No more watches.": "Більше немає годинників.",
        "Unknown command. Please use the menu": "Невідома команда. Будь ласка, скористайтеся меню",
        "Follow": "Стежити",
        "Added to watchlist": "Додано до списку відстеження",
        "Choose price from": "Оберіть ціну від",
        "Choose price to": "Оберіть ціну до",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Ви обрали {watch_name} у діапазоні: від {price_from} до {price_to}. Бажаєте переглянути годинники? Введіть /watches.",
    },
    "pol": {
        "Show my favorite watches:": "Pokaż moje ulubione zegarki:",
        "Delete watch": "Usuń zegarek",
        "Welcome to the Watches Bot! Choose a watch:": "Witamy w Watches Bot! Wybierz zegarek:",
        "Choose a watch:": "Wybierz zegarek:",
        "and select an action": "i wybierz akcję",
        "You don't have any favorite watches": "Nie masz ulubionych zegarków",
        "Your favorite watches": "Twoje ulubione zegarki",
        "Name": "Nazwa",
        "Characteristics": "Charakterystyka",
        "Price": "Cena",
        "Delete": "Usuń",
        "You delete your favorite watches": "Usunąłeś swoje ulubione zegarki",
        "write the name of the watch you want to find": "Napisz nazwę zegarka, który chcesz znaleźć",
        "No watches found for your selection": "Nie znaleziono zegarków dla Twojego wyboru",
        "All your favorite watches have been deleted": "Wszystkie Twoje ulubione zegarki zostały usunięte.",
        "Select an option": "Wybierz opcję",
        "Please select a watch brand first": "Najpierw wybierz markę zegarka",
        "No price found in": "Nie znaleziono ceny w",
        "Price range is not set. Please select price range again.": "Zakres cen nie jest ustawiony. Wybierz zakres cen ponownie.",
        "Send /more to see more watches.": "Wyślij /more, aby zobaczyć więcej zegarków.",
        "No more watches.": "Nie ma więcej zegarków.",
        "Unknown command. Please use the menu": "Nieznane polecenie. Skorzystaj z menu",
        "Follow": "Obserwuj",
        "Added to watchlist": "Dodano do listy obserwowanych",
        "Choose price from": "Wybierz cenę od",
        "Choose price to": "Wybierz cenę do",
        "You have selected {watch_name} a range: from {price_from} to {price_to}. Do you want look /watches ?":
            "Wybrałeś {watch_name} w zakresie: od {price_from} do {price_to}. Chcesz zobaczyć zegarki? Wpisz /watches.",
    }
}